apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mon-chart.fullname" . }}-frontend
  labels:
    {{- include "mon-chart.labels" . | nindent 4 }}
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mon-chart.name" . }}
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "mon-chart.name" . }}
        tier: frontend
    spec:
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: API_URL
              value: {{ .Values.frontend.env.apiUrl | quote }}
          ports:
            - name: app-port
              containerPort: {{ .Values.frontend.containerPort }}
