{{- if .Values.ingress-nginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mon-chart.fullname" . }}-ingress
  labels:
    {{- include "mon-chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mon-chart.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "mon-chart.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
