apiVersion: v1
kind: Service
metadata:
  name: {{ include "mon-chart.fullname" . }}-api
  labels:
    {{- include "mon-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ include "mon-chart.name" . }}
    tier: backend
  ports:
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
