apiVersion: v1
kind: Service
metadata:
  name: recipe-api
  labels:
    app: recipe
spec:
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: recipe
    tier: backend
  type: ClusterIP