apiVersion: v1
kind: Service
metadata:
  name: recipe-mysql
  labels:
    app: recipe
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: recipe
    tier: bdd
  type: ClusterIP