apiVersion: v1
kind: Service
metadata:
  name: {{ include "mon-chart.fullname" . }}-frontend
  labels:
    app: {{ include "mon-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "mon-chart.name" . }}
    tier: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP